sudo: false

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install tox codecov

env:
  - TOX_ENV=flake8

#  - TOX_ENV=py27-tw121
#  - TOX_ENV=py27-tw132
#  - TOX_ENV=py27-tw154
#  - TOX_ENV=py27-tw165
#  - TOX_ENV=py27-twtrunk
#  - TOX_ENV=py27-asyncio
#
#  - TOX_ENV=pypy-tw121
#  - TOX_ENV=pypy-tw132
#  - TOX_ENV=pypy-tw154
#  - TOX_ENV=pypy-tw165
#  - TOX_ENV=pypy-twtrunk
#  - TOX_ENV=pypy-asyncio
#
#  - TOX_ENV=py33-tw154
#  - TOX_ENV=py33-tw165
#  - TOX_ENV=py33-twtrunk
#  - TOX_ENV=py33-asyncio
#
#  - TOX_ENV=py34-tw154
#  - TOX_ENV=py34-tw165
#  - TOX_ENV=py34-twtrunk
#  - TOX_ENV=py34-asyncio

  - TOX_ENV=py35-tw154
  - TOX_ENV=py35-tw165
  - TOX_ENV=py35-twtrunk
  - TOX_ENV=py35-asyncio

  - TOX_ENV=py36-tw154
  - TOX_ENV=py36-tw165
  - TOX_ENV=py36-twtrunk
  - TOX_ENV=py36-asyncio

script:
  - tox -c tox.ini -e $TOX_ENV

after_success:
  # since we use --parallel-mode to coverage inside Tox we use
  # "coverage combine" so the filename is always ".coverage"
  - cd test && coverage combine && codecov

matrix:
  fast_finish: true

notifications:
   irc:
      channels:
         - "irc.freenode.org#autobahn"
      use_notice: true
      skip_join: true
