# https://docs.travis-ci.com/user/languages/python/

language: python
sudo: false

install:
  # wheel has dropped support for py 3.3 with version 0.30.0
  - pip install 'wheel<0.30.0'
  - pip install tox codecov

script:
  - tox -c tox.ini -e $TOX_ENV

after_success:
  # since we use --parallel-mode to coverage inside Tox we use
  # "coverage combine" so the filename is always ".coverage"
  - cd test && coverage combine && codecov

matrix:
  fast_finish: true

  # https://github.com/travis-ci/travis-ci/issues/4794#issuecomment-143758799
  include:
    - env: TOX_ENV=flake8

    - python: 2.7
      env:
      - TOX_ENV=py27-tw121

    - python: 2.7
      env:
      - TOX_ENV=py27-tw132

    - python: 2.7
      env:
      - TOX_ENV=py27-tw154

    - python: 2.7
      env:
      - TOX_ENV=py27-tw165

    - python: 2.7
      env:
      - TOX_ENV=py27-twtrunk

    - python: 2.7
      env:
      - TOX_ENV=py27-asyncio


    - python: pypy
      env:
      - TOX_ENV=pypy-tw121

    - python: pypy
      env:
      - TOX_ENV=pypy-tw132

    - python: pypy
      env:
      - TOX_ENV=pypy-tw154

    - python: pypy
      env:
      - TOX_ENV=pypy-tw165

    - python: pypy
      env:
      - TOX_ENV=pypy-twtrunk

    - python: pypy
      env:
      - TOX_ENV=pypy-asyncio


    - python: pypy3
      env:
      - TOX_ENV=pypy3-tw154

    - python: pypy3
      env:
      - TOX_ENV=pypy3-tw165

    - python: pypy3
      env:
      - TOX_ENV=pypy3-twtrunk

    - python: pypy3
      env:
      - TOX_ENV=pypy3-asyncio


    - python: 3.3
      env:
      - TOX_ENV=py33-tw154

    - python: 3.3
      env:
      - TOX_ENV=py33-tw165

    - python: 3.3
      env:
      - TOX_ENV=py33-asyncio


    - python: 3.4
      env:
      - TOX_ENV=py34-tw154

    - python: 3.4
      env:
      - TOX_ENV=py34-tw165

    - python: 3.4
      env:
      - TOX_ENV=py34-twtrunk

    - python: 3.4
      env:
      - TOX_ENV=py34-asyncio


    - python: 3.5
      env:
      - TOX_ENV=py35-tw154

    - python: 3.5
      env:
      - TOX_ENV=py35-tw165

    - python: 3.5
      env:
      - TOX_ENV=py35-twtrunk

    - python: 3.5
      env:
      - TOX_ENV=py35-asyncio


    - python: 3.6
      env:
      - TOX_ENV=py36-tw154

    - python: 3.6
      env:
      - TOX_ENV=py36-tw165

    - python: 3.6
      env:
      - TOX_ENV=py36-twtrunk

    - python: 3.6
      env:
      - TOX_ENV=py36-asyncio


# CI notifications
notifications:
  # IRC: chat messages on #crossbar-ci @ freenode
  irc:
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always    # options: [always|never|change] default: always
    channels:
      - "irc.freenode.org#crossbar-ci"
    use_notice: false
    skip_join: false

  # Gitter: activity feed on https://gitter.im/crossbario/ci
  webhooks:
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always    # options: [always|never|change] default: always
    urls:
      # travis encrypt "https://webhooks.gitter.im/e/7ef..." --org --repo crossbario/txaio
      - secure: bLUKiR27KsxcAHfCYEP2ZOrk1haqdOAEg9eRqYKopB1k4l8F/EkCBpN+X5+O3AT+wjOyq2msY9dA9jrAyZ1B6J+Dc1WgTihLyB36AVsNQtP3PGEX0jubpxPMnITqorO7saLqdwyKBuF0+8IWqM2MvEaPYy/kHL/utVvKxJy7ljY=

  # Slack: post feed on https://crossbario.slack.com/messages/CAT527K8D
  # https://crossbario.slack.com/services/
  slack:
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always    # options: [always|never|change] default: always
    rooms:
      # travis encrypt "crossbario:FYg..." --org --repo crossbario/txaio
      - secure: dPV0Nr3OtWIw7Af3r0xG4vNTpvjj3I67Mca0knqrplZpSOiSmDKRh1bqcAui557SBYhBpKNkUDQGeRvluTuPHv3TesKZNJGOq0PvDbxRJvCrnwqhRq/JXOFGGs2mC4hGXJ8wS67jn8A38pZSf4MRTGr9fPQKQqpPqXnkw4eokPc=
